name = "ppkpt"
main = ".open-next/worker.js"
compatibility_date = "2024-01-01"

# Mengaktifkan kompatibilitas Node.js karena Next.js membutuhkannya
compatibility_flags = [ "nodejs_compat" ]

# Memastikan assets statis (gambar, css, js pengunjung) ikut terupload
[site]
bucket = ".open-next/assets"

# Konfigurasi caching menggunakan R2 Bucket yang terlihat di dashboard-mu kemarin
[[r2_buckets]]
binding = "NEXT_INC_CACHE_BUCKET"
bucket_name = "ppkpt-opennext-cache"